finish assignment 12
webprogramminghack/assignment-class12 pull request #4
Opened 2024-09-06 04:50 UTC by novelyr

2024-09-15 19:06 UTC, webprogramminghack requested changes

2024-09-15 19:06 UTC, webprogramminghack commented on script/index.js
> +      <p>${task.text}</p>
cara merender text dan tombol actionnya kurang tepat

2024-10-03 15:02 UTC, novelyr commented on script/index.js
> +      <p>${task.text}</p>
Sudah diganti ke cara lain pak

2025-01-09 06:59 UTC, webprogramminghack approved these changes
Assignment completed, good job

2025-01-09 06:59 UTC, closed without merging